os: linux
dist: trusty

sudo: required

addons:
  apt:
    packages:
    - axel
    - build-essential
    - cpanminus
    - libgd-dev
    - liblist-moreutils-perl
    - libncurses5-dev
    - libpcre3-dev
    - libreadline-dev
    - libssl-dev
    - libtest-base-perl
    - libtest-longstring-perl
    - libtext-diff-perl
    - liburi-perl
    - libwww-perl
    - perl
    - valgrind

cache:
  directories:
  - download-cache

env:
  global:
    - JOBS=2
    - OPENRESTY_PREFIX=/usr/local/openresty
    - OPENRESTY_VER=1.11.2.3
  jobs:
    - TEST_NGINX_USE_VALGRIND=0
    - TEST_NGINX_USE_VALGRIND=1

install:
- if [ ! -f download-cache/openresty-$OPENRESTY_VER.tar.gz ]; then
    wget -P download-cache https://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz;
  fi
- git clone https://github.com/openresty/test-nginx.git ../test-nginx

script:
- if [ TEST_NGINX_USE_VALGRIND = 1 ]; then export luajit_xcflags='-DLUAJIT_USE_VALGRIND -DLUAJIT_USE_SYSMALLOC'; fi
- tar xzf download-cache/openresty-$OPENRESTY_VER.tar.gz &&
    cd openresty-$OPENRESTY_VER
- ./configure --prefix=$OPENRESTY_PREFIX --with-luajit-xcflags="$luajit_xcflags" -j$JOBS
    > build.log 2>&1 || (cat build.log && exit 1)
- make -j$JOBS > build.log 2>&1 ||
    (cat build.log && exit 1)
- sudo make install > build.log 2>&1 ||
    (cat build.log && exit 1)
- cd ..
- export PATH=$OPENRESTY_PREFIX/nginx/sbin:$PATH
- make test jobs=$JOBS
